### ISSUE TITLE
Removed Seaside 2 and Intrigue Expansion Pack

### ISSUE THREAD

**Issue by matteioo** [gillesgros/KingdomCreator-New#1]
Hi,

I was wondering if the removal of Seaside 2 and the Intrigue Expansion Pack was done on purpose because I used your webpage instead of the ["original" one](https://github.com/blakevanlan/KingdomCreator). Due to the fact that the "original" one doesn't have those sets I was using yours until there were made some changes which removed those sets.

It would be very nice if you could reimplement them in your project.

Kind regards.

**Comment by gillesgros** [comment]
Hello,

Seaside 2 is not removed. each of the expansions that have 1st and 2nd edition are on 1 line for randomize.
if you have 1st edition and update pack use 1st and 2nd edition
![image](https://user-images.githubusercontent.com/39326434/190318916-0dc52816-b419-453d-8043-72d0ce6bddc7.png)

hope this help, otherwise, can you be more explicit and I will see what I can do.

**Comment by matteioo** [comment]
Last Monday when I wanted to use your app there was no 2nd edition Seaside but it seems that either I didn't see it or there was some sort of displaying issue - next time I'll take a screenshot.

Furthermore in your app there was the ability to select the update pack only. Some time ago I had bought the Update Pack which at the time I didn't know that it's purpose is to only replace some cards from the first version but I never bought the first or second edition of Intrigue and therefore I have only a small portion of the second edition Intrigue. Therefore it was very convenient beeing able to select the update pack in the list of cards and therefore I didn't have to reroll multiple times to create a deck of which I had all cards.

**Comment by gillesgros** [comment]
Ok, I understand the need for having the UpdatePack only. I will work on it soon.
If you have an idea of menu display, feel free.

**Comment by gillesgros** [comment]
Implemented
