### ISSUE TITLE
Cards not flipping

### ISSUE THREAD

**Issue by FayDn93** [gillesgros/KingdomCreator-New#3]
Hi.

I have been a long-time user of your marvellous site. It has worked like a charm up until now. Today I noticed an issue on both the mobile and computer versions. The site still randomizes the cards but the only way to see which card it randomized to the next game is to read them from the address bar. For some reason, the cards are not flipping and only show the card's back sides. 

Thank you in advance!

-FayDn

**Comment by gillesgros** [comment]
Thank. I will work on it tonight

**Comment by gillesgros** [comment]
Fixed
